# checks:
#   javascript: true

build:
  nodes:
    jsramverk-frontend:
      # dependencies:
      #   before:
      #     - "nvm install 14.5.0"      
      environment:
        node: "v10.14.2"
      #   selenium:
      #     browser_name: chrome
      # tests:
      #   override:
      #     -
      #       command: npm run test-scrutinizer
      #       coverage:
      #         file: build/coverage/clover.xml
      #         format: clover