# checks:
#   javascript: true

build:
  nodes:
    jsramverk-frontend:
      dependencies:
        override:
          - "nvm install v13.13.0"      
      # environment:
      #   node: "14.0.0"
      #   selenium:
      #     browser_name: chrome
      # tests:
      #   override:
      #     -
      #       command: npm run test-scrutinizer
      #       coverage:
      #         file: build/coverage/clover.xml
      #         format: clover