# checks:
#   javascript: true

build:
  nodes:
    jsramverk-frontend:
      environment:
        dependencies:
          before:
            - "nvm install v14.5.0"              
        node: "v14.5.0"
      #   selenium:
      #     browser_name: chrome
      # tests:
      #   override:
      #     -
      #       command: npm run test-scrutinizer
      #       coverage:
      #         file: build/coverage/clover.xml
      #         format: clover