checks:
  javascript: true

build:
  nodes:
    jsramverk-frontend:
      environment:
        selenium: true
      dependencies:
        override:
          - "nvm install v13.13.0"
          - npm install
          - chromedriver &
      tests:
        override:    
          - 
            command: npm run test-scrutinizer
            coverage:
              file: build/coverage/clover.xml
              format: clover