# checks:
#   javascript: true

build:
  nodes:
    jsramverk-frontend:
      dependencies:
        override:
          - "nvm install v13.13.0"
      environment:
        selenium:
          browser_name: chrome
      tests:
        override:
          -
            commands: 
              - npm run test-scrutinizer
              - npm install
                coverage:
                  file: build/coverage/clover.xml
                  format: clover