checks:
  javascript: true

build:
  nodes:
    functional-tests:
      environment:
        selenium: true
    jsramverk-frontend:
      dependencies:
        override:
          - "nvm install v13.13.0"
          - npm install
          - npm run test-scrutinizer 
      # tests:
      #   override:
      #     - npm install
      #     - npm run test-scrutinizer
            # coverage:
            #   file: build/coverage/clover.xml
            #   format: clover