dist: xenial

language: node_js
node_js: "14.5.0"

addons:
  chrome: stable

# before_install:
#   - sudo apt-get update
#   - sudo apt-get -y install curl
#   - curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
#   - sudo bash nodesource_setup.sh
#   - sudo apt-get -y install nodejs

before_install:
  # - sudo apt-get update
  # - sudo apt-get install -y chromium-chromedriver
  - npm install
  - npm run start &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9515 https://kryman.me &

# install: npm install

# before_script:
#   - screen -d -m -S chromedriver -s chromedriver

script: 
- npm run test
- npm run test2