dist: xenial

language: node_js
node_js: "14.5.0"

addons:
  chrome: stable

before_install:
  - sudo apt-get update
  - sudo apt-get install -y chromium-chromedriver

install: npm install

script: npm run test