language: node_js

before_install:
  - sudo apt-get update
  - sudo apt-get -y install curl
  - curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
  - sudo bash nodesource_setup.sh
  - sudo apt-get -y install nodejs

install: npm install

script: 
  - npm start
  - npm test